set -s escape-time 50
set -g mouse on
set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection

set-option -s set-clipboard on
set-option -g pane-scrollbars on

bind -n S-Enter send-keys Escape "[13;2u"
